### ISSUE TITLE
ReactNavbar needs changed to dark styling.

### ISSUE THREAD

**Issue by movarnell** [movarnell/Fan-Prom-Ango#4]
### Simple Change to Dark
If you're looking to jump on an easy contribution, the Navbar needs converted to dark. This was made using react-bootstrap and you can easily read about how to change it on [React Bootstrap's Navbar Page](https://react-bootstrap.netlify.app/docs/components/navbar) where they have all the options. 

Remember to use the proper branch when working on this. Assign yourself if you are working on this!

**Comment by marcoarnulfo** [comment]
Hi! I'm not one of your students, is it still possible to join your Slack to contribute? :)

**Comment by movarnell** [comment]
Unfortunately if your not a student with Promineo Tech's bootcamp we can't add you to our slack to participate. If you started the bootcamp, then you would have access to the meetings, but I am not sure if you were interested in doing the Front End bootcamp, if you are you can email me at michael.varnell@promineo.tech and I can get you in touch with our admissions team.

**Comment by marcoarnulfo** [comment]
Thank you anyway for the interest and the opportunity, but I was looking for some issues to contribute to.
